### ISSUE TITLE
Issues Running With Ice Source Code

### ISSUE THREAD

**Issue by Teutonic84** [perezdev/RetroGamingCloudDotNet#1]
Hi i'm having problems getting this working with the ICE application's source code from here: https://github.com/scottrice/Ice

Ice works perfectly fine and downloads all the grid images it can from the old consolegrid website, but when I change the source URL to https://retrogaming.cloud/api/v1/game/mostPopular it doesn't download any images. It runs ICE without any grid image provider errors, so it sees it but doesn't do anything. Since i'm using the latest source code from the github page for ICE, the config file is a little different. it only has the provider options of "local" and "consolegrid". So I had to go into "ice\gridproviders\consolegrid_provider.py" and edit the line that had this for the api url: "http://consolegrid.com/api/top_picture".

**Comment by perezdev** [comment]
You'll need to ask Chris, the maintainer of the REST API. This is just a .NET wrapper for that API.

https://www.reddit.com/user/chriscalifornia88
